### ISSUE TITLE
About iSeg2017 datasets

### ISSUE THREAD

**Issue by wenwenyu** [LU4E/kerasBra4Tensorflow#1]
Hi
When I download iSeg2017 datasets from [there](http://iseg2017.web.unc.edu/download/) .It request create a team firstly from [there](https://form.jotform.us/form/70697708695172) ,but this link is not work.Do you have the same problem? If you not, can you provide iSeg2017 datasets due to I can't download.
Thinks!

**Comment by LU4E** [comment]
The database needs permission.

We signed a confidentiality agreement.

If you need it, you can register the team with the name of the institution
to get the database access.

Sorry.

If you can afford some details about your identity, I will talk with my
partner about the use of the data.



Wenwen Yu <notifications@github.com>于2018年5月14日 周一00:43写道：

**Comment by WENWENYU** [comment]
@LU4E The website that register the team is not accssable.How can i get dataset. Can you provide datasets

**Comment by LU4E** [comment]
I am sorry.
I have no right to provide the dataset.

**Comment by WENWENYU** [comment]
Thinks，I understand that. Can you teach me to register the team. I not sure how to register team.
